name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
          -t yashkjha/nivasa-react:latest \
          --build-arg REACT_APP_NODE_ENV='production' \
          --build-arg VITE_API_BASE_URL='${{ secrets.VITE_API_BASE_URL }}' .

      - name: Publish Image to Docker Hub
        run: docker push yashkjha/nivasa-react:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull yashkjha/nivasa-react:latest

      - name: Delete Old Container
        run: |
          if [ $(docker ps -aq -f name=reactjs-app-container) ]; then
            docker rm -f reactjs-app-container;
          fi

      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 \
          -e VITE_API_BASE_URL='${{ secrets.VITE_API_BASE_URL }}' \
          --name reactjs-app-container \
          yashkjha/nivasa-react:latest
